### ISSUE TITLE
Support for Ubuntu 14.04 ?

### ISSUE THREAD

**Issue by kimthostrup** [raurodse/network_interfaces_parser#3]
Hi Raul,

Do you have any plans for adding ubuntu 14.04 ?

New interfaces format (note hashmarks replaced with // due to github's parsing and readability)
----snip----
kim@ubuntu-server:~$ cat /etc/network/interfaces
//This file describes the network interfaces available on your system
//and how to activate them. For more information, see interfaces(5).

//The loopback network interface
auto lo
iface lo inet loopback

//The primary network interface
auto eth0
iface eth0 inet static
    address 10.20.1.3
    netmask 255.255.255.0
    network 10.20.1.0
    broadcast 10.20.1.255
    gateway 10.20.1.1
    # dns-\* options are implemented by the resolvconf package, if installed
    dns-nameservers 10.20.1.1
    dns-search example.com

auto eth1
iface eth1 inet static
    address 192.168.10.239
    netmask 255.255.255.0
    network 192.168.10.1
    broadcast 192.168.10.255
    gateway 192.168.10.1
    # dns-\* options are implemented by the resolvconf package, if installed
    dns-nameservers 192.168.10.1
    dns-search example.com
----snip----
/Kim

**Comment by raurodse** [comment]
Hi kimthostrup, I installed Ubuntu Server 14.04 on VirtualBox, but i don't find anything about slash ("/"). 
How did you get this file? 
However, i add support for slash now

**Comment by kimthostrup** [comment]
Hi Raul,

I got it from a clean install of a ubuntu server 14.04 ;)
Anyway some more troubleshooting lead me to a solution: https://github.com/metral/restore_networking
It turns out Ubuntu decided to change networking scripts, see also : http://askubuntu.com/questions/441619/how-to-successfully-restart-a-network-without-reboot-over-ssh

/Kim
